import { useState } from "react";
import { ArrowLeft, BarChart3, CheckCircle2, Code2, ExternalLink, Globe2, Lightbulb, Users } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { SiteNav } from "@/components/site-nav";
import { SiteFooter } from "@/components/site-footer";
import { CodeBlock } from "@/components/code-block";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from "recharts";

const sourceUrl = "https://archive.ics.uci.edu/dataset/352/online+retail";
const kpis = [
  { label: "Completed-sales revenue", value: "£10.64M", note: "After excluding cancellations and invalid sale lines" },
  { label: "Completed orders", value: "19,960", note: "Unique invoices in the analytical sales view" },
  { label: "Identified customers", value: "4,338", note: "Customer-level analysis uses identifiable customers" },
  { label: "Units sold", value: "5.57M", note: "Positive-quantity sale lines" },
  { label: "Average order value", value: "~£533", note: "Revenue divided by completed orders" },
  { label: "UK revenue share", value: "84.59%", note: "The domestic market dominates revenue" },
];
const productData = [
  { name: "Regency Cakestand 3 Tier", value: 164762.19 },
  { name: "White Hanging Heart T-Light Holder", value: 99668.47 },
  { name: "Party Bunting", value: 98302.98 },
  { name: "Jumbo Bag Red Retrospot", value: 92356.03 },
  { name: "Rabbit Night Light", value: 66756.59 },
];
const countryData = [
  { name: "United Kingdom", value: 84.59 }, { name: "EIRE", value: 5.8 }, { name: "Netherlands", value: 2.7 }, { name: "Germany", value: 1.9 }, { name: "Other markets", value: 5.01 },
];
const monthlyData = [
  { month: "Dec 2010", revenue: 821452.73, orders: 1559, aov: 526.91 }, { month: "Jan 2011", revenue: 689811.61, orders: 1086, aov: 635.19 }, { month: "Feb 2011", revenue: 522545.56, orders: 1100, aov: 475.04 }, { month: "Mar 2011", revenue: 716215.26, orders: 1454, aov: 492.58 }, { month: "Apr 2011", revenue: 536968.49, orders: 1246, aov: 430.95 }, { month: "May 2011", revenue: 769296.61, orders: 1681, aov: 457.64 }, { month: "Jun 2011", revenue: 760547.01, orders: 1533, aov: 496.12 }, { month: "Jul 2011", revenue: 718076.12, orders: 1475, aov: 486.83 }, { month: "Aug 2011", revenue: 757841.38, orders: 1361, aov: 556.83 }, { month: "Sep 2011", revenue: 1056435.19, orders: 1837, aov: 575.09 }, { month: "Oct 2011", revenue: 1151263.73, orders: 2040, aov: 564.34 }, { month: "Nov 2011", revenue: 1503866.78, orders: 2769, aov: 543.11 }, { month: "Dec 2011", revenue: 637790.33, orders: 819, aov: 778.74 },
];
const productScatter = [
  { product: "REGENCY CAKESTAND 3 TIER", units: 13851, revenue: 174156.54 }, { product: "PAPER CRAFT LITTLE BIRDIE", units: 80995, revenue: 168469.6 }, { product: "WHITE HANGING HEART", units: 37580, revenue: 104284.24 }, { product: "PARTY BUNTING", units: 18283, revenue: 99445.23 }, { product: "JUMBO BAG RED RETROSPOT", units: 48371, revenue: 94159.81 }, { product: "MEDIUM CERAMIC STORAGE JAR", units: 78033, revenue: 81700.92 }, { product: "RABBIT NIGHT LIGHT", units: 30739, revenue: 66870.03 }, { product: "PAPER CHAIN CHRISTMAS", units: 19329, revenue: 64875.59 }, { product: "BIRD ORNAMENT", units: 36362, revenue: 58927.62 }, { product: "CHILLI LIGHTS", units: 10302, revenue: 54096.36 }, { product: "SPOTTY BUNTING", units: 8320, revenue: 42513.48 }, { product: "JUMBO BAG PINK POLKADOT", units: 21448, revenue: 42401.01 }, { product: "BLACK RECORD COVER FRAME", units: 11651, revenue: 40633.38 }, { product: "PICNIC BASKET 60 PIECES", units: 61, revenue: 39619.5 }, { product: "DOORMAT KEEP CALM", units: 5487, revenue: 38133.64 }, { product: "SET OF 3 CAKE TINS", units: 7483, revenue: 38108.89 }, { product: "JAM MAKING SET WITH JARS", units: 8695, revenue: 37082.13 }, { product: "WOOD BLACK BOARD", units: 6012, revenue: 35966.92 }, { product: "LUNCH BAG RED RETROSPOT", units: 19232, revenue: 35572.36 }, { product: "POPCORN HOLDER", units: 36749, revenue: 34288.67 },
];
const productConcentration = [{ group: "Top 1%", share: 19.57 }, { group: "Top 5%", share: 46.14 }, { group: "Top 10%", share: 62.27 }, { group: "Top 20%", share: 79.18 }, { group: "Top 50%", share: 96.31 }];
const customerConcentration = [{ group: "Top 1%", share: 32.06 }, { group: "Top 5%", share: 50.46 }, { group: "Top 10%", share: 61.45 }, { group: "Top 20%", share: 74.68 }, { group: "Top 50%", share: 92.19 }];
const cancellationData = [
  { month: "Dec 2010", invoices: 326, value: 74789.12 }, { month: "Jan 2011", invoices: 260, value: 131364.3 }, { month: "Feb 2011", invoices: 219, value: 25569.24 }, { month: "Mar 2011", invoices: 318, value: 34372.28 }, { month: "Apr 2011", invoices: 240, value: 44601.5 }, { month: "May 2011", invoices: 314, value: 47202.51 }, { month: "Jun 2011", invoices: 329, value: 70616.78 }, { month: "Jul 2011", invoices: 270, value: 37921.08 }, { month: "Aug 2011", invoices: 278, value: 54333.75 }, { month: "Sep 2011", invoices: 333, value: 38902.55 }, { month: "Oct 2011", invoices: 362, value: 84274.63 }, { month: "Nov 2011", invoices: 441, value: 47740.08 }, { month: "Dec 2011", invoices: 146, value: 205124.67 },
];
const codeSnippets = [
  { title: "01 · Data Loading", description: "Load the complete UCI record set directly through the UCI ML Repository package.", code: `from ucimlrepo import fetch_ucirepo\n\nonline_retail = fetch_ucirepo(id=352)\ndf = online_retail.data.original.copy()\nprint(df.shape)\nprint(df.head())` },
  { title: "02 · Data Quality Audit", description: "Measure the issues that can materially affect sales and customer analysis before making cleaning decisions.", code: `missing = (\n    df.isna().sum().to_frame("missing_rows")\n      .assign(missing_pct=lambda x: x["missing_rows"] / len(df) * 100)\n      .sort_values("missing_rows", ascending=False)\n)\nduplicate_rows = df.duplicated().sum()\nis_cancelled = df["InvoiceNo"].astype(str).str.startswith("C")\nnegative_quantity = (df["Quantity"] < 0).sum()\ninvalid_price = (df["UnitPrice"] <= 0).sum()` },
  { title: "03 · Feature Engineering", description: "Create the transaction-level revenue measure and analytical sales view.", code: `df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])\ndf["Revenue"] = df["Quantity"] * df["UnitPrice"]\n\nsales = df.loc[\n    (~df["InvoiceNo"].astype(str).str.startswith("C"))\n    & (df["Quantity"] > 0)\n    & (df["UnitPrice"] > 0)\n].drop_duplicates().copy()\n\n# Keep anonymous transactions for overall sales analysis.` },
  { title: "04 · Sales Analysis", description: "Calculate monthly revenue, orders and average order value.", code: `total_revenue = sales["Revenue"].sum()\norders = sales["InvoiceNo"].nunique()\nunits = sales["Quantity"].sum()\naov = total_revenue / orders\n\nmonthly = (\n    sales.assign(Month=sales["InvoiceDate"].dt.to_period("M"))\n         .groupby("Month")\n         .agg(Revenue=("Revenue", "sum"), Orders=("InvoiceNo", "nunique"))\n         .reset_index()\n)\nmonthly["AOV"] = monthly["Revenue"] / monthly["Orders"]` },
  { title: "05 · Product Analysis", description: "Compare product volume with revenue and measure product revenue concentration.", code: `product_sales = sales.groupby(["StockCode", "Description"]).agg(\n    Revenue=("Revenue", "sum"),\n    Units=("Quantity", "sum")\n).reset_index()\n\n# Remove non-merchandise service lines for product analysis.\nservice_terms = r"postage|manual|amazon fee|bank charges|discount|samples?|dotcom|adjustment|check"\nproducts = product_sales[\n    ~product_sales["Description"].fillna("").str.contains(service_terms, case=False, regex=True)\n].sort_values("Revenue", ascending=False)\n\ntop_products = products.head(20)\n\nproducts["cumulative_share"] = (\n    products["Revenue"].cumsum() / products["Revenue"].sum() * 100\n)` },
  { title: "06 · Customer Analysis", description: "Calculate customer revenue and measure how concentrated revenue is among identified customers.", code: `customer_sales = sales.dropna(subset=["CustomerID"]).copy()\n\ncustomer_summary = (\n    customer_sales.groupby("CustomerID")\n    .agg(Revenue=("Revenue", "sum"), Orders=("InvoiceNo", "nunique"))\n    .reset_index()\n    .sort_values("Revenue", ascending=False)\n)\n\nfor pct in [1, 5, 10, 20, 50]:\n    n = int(np.ceil(len(customer_summary) * pct / 100))\n    share = customer_summary.head(n)["Revenue"].sum() / customer_summary["Revenue"].sum() * 100\n    print(f"Top {pct}%: {share:.2f}% of revenue")` },
  { title: "07 · Cancellation Analysis", description: "Measure cancelled invoices and cancelled value by month.", code: `cancelled = df[df["InvoiceNo"].astype(str).str.startswith("C")].copy()\n\ncancelled_monthly = (\n    cancelled.assign(Month=cancelled["InvoiceDate"].dt.to_period("M"))\n    .groupby("Month")\n    .agg(\n        CancelledInvoices=("InvoiceNo", "nunique"),\n        CancelledUnits=("Quantity", lambda x: -x[x < 0].sum()),\n        CancelledValue=("Revenue", lambda x: -x[x < 0].sum()),\n    )\n    .reset_index()\n)` },
];
function formatGBP(value: number) { return `£${value.toLocaleString("en-GB", { maximumFractionDigits: 0 })}`; }
function ChartCard({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="card-surface p-7"><h3 className="text-lg font-bold tracking-tight">{title}</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{description}</p><div className="mt-5 h-72 w-full">{children}</div></div>; }
function MoneyTooltip(props: any) { return <Tooltip {...props} />; }

export function RetailSalesIntelligence() {
  const [activeCode, setActiveCode] = useState(0);
  const maxProduct = productData[0].value;
  return <div className="min-h-screen bg-background text-foreground antialiased selection:bg-primary/20"><SiteNav /><main className="pb-20">
    <header className="border-b border-border bg-surface/60"><div className="container-page py-10 sm:py-14"><Link to="/" hash="projects" className="inline-flex items-center gap-2 text-xs font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5" /> Back to all projects</Link><div className="mt-6 flex flex-wrap items-center gap-2"><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">Business Analytics</span><span className="text-xs text-muted-foreground">•</span><span className="text-xs text-muted-foreground">Python · Pandas · EDA</span></div><h1 className="mt-4 max-w-4xl text-3xl font-bold tracking-tight text-balance sm:text-4xl lg:text-5xl">Retail Sales Intelligence &amp; Customer Analytics</h1><p className="mt-4 max-w-3xl text-base leading-relaxed text-muted-foreground sm:text-lg">Turning 541,909 transaction-line records into a commercial view of sales performance, product concentration, customer value, seasonality, and market opportunity.</p><div className="mt-6 flex flex-wrap items-center gap-2">{["Python","Pandas","NumPy","Matplotlib","Seaborn","Business Analytics"].map(tool => <span key={tool} className="rounded-md border border-border bg-card px-2.5 py-1 text-xs font-medium text-muted-foreground shadow-2xs">{tool}</span>)}</div><div className="mt-7 flex flex-wrap gap-3"><a href={sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-2 text-xs font-semibold text-foreground hover:bg-accent">UCI Dataset <ExternalLink className="size-3.5" /></a><a href="#code" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground"><Code2 className="size-3.5" /> Show Code</a></div></div></header>
    <div className="container-page mt-12 space-y-16">
      <section><div className="flex items-center gap-2 text-primary"><BarChart3 className="size-5" /><h2 className="text-sm font-semibold uppercase tracking-wider">Executive Snapshot</h2></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{kpis.map(kpi => <div key={kpi.label} className="card-surface p-5"><span className="text-xs font-medium text-muted-foreground">{kpi.label}</span><p className="mt-2 text-3xl font-extrabold tracking-tight">{kpi.value}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{kpi.note}</p></div>)}</div></section>
      <section className="grid gap-8 lg:grid-cols-2"><div className="card-surface p-7"><div className="flex items-center gap-2 text-primary"><Users className="size-5" /><h2 className="text-lg font-bold">Business Question</h2></div><p className="mt-4 text-sm leading-relaxed text-muted-foreground">Management needs to understand where revenue comes from, when demand peaks, which products drive sales, how dependent the business is on its highest-value customers, and which markets deserve attention.</p><div className="mt-5 border-t border-border pt-5"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Business Objective</p><p className="mt-2 text-sm leading-relaxed text-foreground">Understand sales performance, identify the products and customers driving revenue, and highlight opportunities across different markets.</p></div></div><div className="card-surface p-7"><div className="flex items-center gap-2 text-primary"><Globe2 className="size-5" /><h2 className="text-lg font-bold">Dataset</h2></div><p className="mt-4 text-sm leading-relaxed text-muted-foreground">The UCI Online Retail dataset contains transactions from a UK-based non-store online retailer between 1 December 2010 and 9 December 2011. It contains 541,909 records and eight transaction fields.</p><div className="mt-5 grid grid-cols-2 gap-3 text-xs">{["541,909 rows","8 fields","38 countries","Dec 2010–Dec 2011"].map(item => <div key={item} className="rounded-lg border border-border bg-surface p-3 font-medium text-muted-foreground">{item}</div>)}</div></div></section>
      <section className="grid gap-8 lg:grid-cols-2"><div className="card-surface p-7"><span className="text-xs font-semibold uppercase tracking-wider text-primary">Product performance</span><h2 className="mt-1 text-2xl font-bold">Top products by revenue</h2><p className="mt-2 text-xs text-muted-foreground">Service and postage codes are separated from the product story where appropriate.</p><div className="mt-6 space-y-4">{productData.map((p,i)=><div key={p.name}><div className="mb-1 flex items-center justify-between gap-4 text-xs"><span className="font-medium">{i+1}. {p.name}</span><span className="font-semibold text-primary">{formatGBP(p.value)}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${p.value/maxProduct*100}%`}} /></div></div>)}</div></div><div className="card-surface p-7"><span className="text-xs font-semibold uppercase tracking-wider text-primary">Market concentration</span><h2 className="mt-1 text-2xl font-bold">Revenue is heavily concentrated in the UK</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">The international share is meaningful, but no individual overseas market approaches the domestic revenue base.</p><div className="mt-7 space-y-4">{countryData.map(c=><div key={c.name}><div className="mb-1 flex items-center justify-between text-xs"><span className="font-medium">{c.name}</span><span className="font-semibold text-primary">{c.value.toFixed(2)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${Math.max(c.value,2)}%`}} /></div></div>)}</div></div></section>
      <section><div className="mb-5"><span className="text-xs font-semibold uppercase tracking-wider text-primary">Sales performance</span><h2 className="mt-1 text-2xl font-bold">Revenue, orders and average order value over time</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">Monthly views make the seasonal ramp visible and separate changes in revenue from changes in order volume and order value.</p></div><div className="grid gap-8 lg:grid-cols-2"><ChartCard title="Monthly revenue" description="Completed-sales revenue by month."><ResponsiveContainer width="100%" height="100%"><LineChart data={monthlyData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" angle={-35} textAnchor="end" height={65}/><YAxis tickFormatter={v=>`£${(v/1000000).toFixed(1)}M`}/><Tooltip formatter={(v)=>formatGBP(Number(v))}/><Line type="monotone" dataKey="revenue" stroke="currentColor" strokeWidth={2.5}/></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Monthly orders" description="Unique completed invoices by month."><ResponsiveContainer width="100%" height="100%"><BarChart data={monthlyData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" angle={-35} textAnchor="end" height={65}/><YAxis/><Tooltip/><Bar dataKey="orders" fill="currentColor" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Average order value" description="Revenue divided by completed orders for each month."><ResponsiveContainer width="100%" height="100%"><LineChart data={monthlyData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" angle={-35} textAnchor="end" height={65}/><YAxis tickFormatter={v=>`£${v}`}/><Tooltip formatter={(v)=>formatGBP(Number(v))}/><Line type="monotone" dataKey="aov" stroke="currentColor" strokeWidth={2.5}/></LineChart></ResponsiveContainer></ChartCard></div></section>
      <section><div className="mb-5"><span className="text-xs font-semibold uppercase tracking-wider text-primary">Product economics</span><h2 className="mt-1 text-2xl font-bold">Volume does not always translate directly into revenue</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">The scatter view compares units sold with revenue across the highest-revenue merchandise products.</p></div><ChartCard title="Product volume vs revenue" description="Top 20 merchandise products by revenue; each point represents one product."><ResponsiveContainer width="100%" height="100%"><ScatterChart><CartesianGrid/><XAxis type="number" dataKey="units" name="Units"/><YAxis type="number" dataKey="revenue" name="Revenue" tickFormatter={v=>`£${(v/1000).toFixed(0)}k`}/><Tooltip cursor={{strokeDasharray:"3 3"}} formatter={(v)=>formatGBP(Number(v))}/><Scatter data={productScatter} fill="currentColor"/></ScatterChart></ResponsiveContainer></ChartCard></section>
      <section className="grid gap-8 lg:grid-cols-2"><ChartCard title="Product revenue concentration" description="Share of merchandise revenue generated by the highest-revenue product groups."><ResponsiveContainer width="100%" height="100%"><BarChart data={productConcentration}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="group"/><YAxis tickFormatter={v=>`${v}%`}/><Tooltip formatter={(v)=>`${Number(v).toFixed(2)}%`}/><Bar dataKey="share" fill="currentColor" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Customer revenue concentration" description="Share of identified-customer revenue generated by the highest-value customer groups."><ResponsiveContainer width="100%" height="100%"><BarChart data={customerConcentration}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="group"/><YAxis tickFormatter={v=>`${v}%`}/><Tooltip formatter={(v)=>`${Number(v).toFixed(2)}%`}/><Bar dataKey="share" fill="currentColor" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></ChartCard></section>
      <section><div className="mb-5"><span className="text-xs font-semibold uppercase tracking-wider text-primary">Cancellations &amp; returns</span><h2 className="mt-1 text-2xl font-bold">Cancelled invoices and cancelled value vary by month</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">Cancelled invoice numbers are identified by the <code>C</code> prefix. The analysis separates cancellation frequency from the value associated with cancelled lines.</p></div><div className="grid gap-8 lg:grid-cols-2"><ChartCard title="Cancelled invoices by month" description="Unique invoice numbers marked as cancelled."><ResponsiveContainer width="100%" height="100%"><BarChart data={cancellationData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" angle={-35} textAnchor="end" height={65}/><YAxis/><Tooltip/><Bar dataKey="invoices" fill="currentColor" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Cancelled value by month" description="Absolute value of negative cancelled sales lines."><ResponsiveContainer width="100%" height="100%"><LineChart data={cancellationData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" angle={-35} textAnchor="end" height={65}/><YAxis tickFormatter={v=>`£${(v/1000).toFixed(0)}k`}/><Tooltip formatter={(v)=>formatGBP(Number(v))}/><Line type="monotone" dataKey="value" stroke="currentColor" strokeWidth={2.5}/></LineChart></ResponsiveContainer></ChartCard></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><div className="card-surface p-5"><span className="text-xs text-muted-foreground">Cancelled invoices</span><p className="mt-2 text-2xl font-bold">3,836</p><p className="mt-1 text-xs text-muted-foreground">14.81% of 25,900 invoice numbers</p></div><div className="card-surface p-5"><span className="text-xs text-muted-foreground">Cancelled units</span><p className="mt-2 text-2xl font-bold">277,574</p><p className="mt-1 text-xs text-muted-foreground">Based on negative-quantity cancelled lines</p></div><div className="card-surface p-5"><span className="text-xs text-muted-foreground">Cancelled value</span><p className="mt-2 text-2xl font-bold">£896,812</p><p className="mt-1 text-xs text-muted-foreground">Absolute value of cancelled lines</p></div></div></section>
      <section id="code" className="scroll-mt-24"><div className="flex items-center gap-2 text-primary"><Code2 className="size-5"/><h2 className="text-2xl font-bold">Show Code</h2></div><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Selected Python used for the retail analysis.</p><div className="mt-6 overflow-hidden rounded-xl border border-border bg-card"><div className="flex flex-wrap border-b border-border">{codeSnippets.map((s,i)=><button key={s.title} onClick={()=>setActiveCode(i)} className={`px-4 py-3 text-xs font-semibold ${activeCode===i?"bg-primary/10 text-primary":"text-muted-foreground hover:bg-accent hover:text-foreground"}`}>{s.title}</button>)}</div><div className="p-5"><p className="mb-3 text-sm text-muted-foreground">{codeSnippets[activeCode].description}</p><CodeBlock code={codeSnippets[activeCode].code} language="python" /></div></div></section>
      <section><div className="flex items-center gap-2 text-primary"><Lightbulb className="size-5"/><h2 className="text-2xl font-bold">Key Findings &amp; Recommendations</h2></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="card-surface p-6"><div className="flex items-center gap-2"><CheckCircle2 className="size-5 text-primary"/><h3 className="font-bold">Findings</h3></div><ul className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground"><li>• Revenue is strongly concentrated in the UK market.</li><li>• A small group of products contributes a disproportionate share of sales.</li><li>• November is the strongest full month in the available period.</li><li>• Customer revenue is also concentrated among a relatively small group of identified customers.</li></ul></div><div className="card-surface p-6"><h3 className="font-bold">Recommendations</h3><ul className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground"><li>• Prioritize availability of high-revenue products.</li><li>• Use customer value to prioritize key accounts.</li><li>• Treat the UK as the core market while evaluating overseas growth opportunities.</li><li>• Use seasonal demand patterns when planning inventory and campaigns.</li></ul></div></div></section>
    </div></main><SiteFooter /></div>;
}
