import { useState } from "react";
import { ArrowLeft, BarChart3, Code2, ExternalLink, Globe2, Users } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { SiteNav } from "@/components/site-nav";
import { SiteFooter } from "@/components/site-footer";
import { CodeBlock } from "@/components/code-block";

const sourceUrl = "https://archive.ics.uci.edu/dataset/352/online+retail";
const kpis = [
  ["Completed-sales revenue", "£10.64M", "After excluding cancellations and invalid sale lines"],
  ["Completed orders", "19,960", "Unique invoices in the analytical sales view"],
  ["Identified customers", "4,338", "Customer-level analysis uses identifiable customers"],
  ["Units sold", "5.57M", "Positive-quantity sale lines"],
  ["Average order value", "~£533", "Revenue divided by completed orders"],
  ["UK revenue share", "84.59%", "The domestic market dominates revenue"],
] as const;
const products = [
  ["Regency Cakestand 3 Tier", 164762.19], ["White Hanging Heart T-Light Holder", 99668.47], ["Party Bunting", 98302.98], ["Jumbo Bag Red Retrospot", 92356.03], ["Rabbit Night Light", 66756.59],
] as const;
const countries = [["United Kingdom",84.59],["EIRE",5.8],["Netherlands",2.7],["Germany",1.9],["Other markets",5.01]] as const;
const monthly = [
  ["Dec 2010",821452.73,1559,526.91],["Jan 2011",689811.61,1086,635.19],["Feb 2011",522545.56,1100,475.04],["Mar 2011",716215.26,1454,492.58],["Apr 2011",536968.49,1246,430.95],["May 2011",769296.61,1681,457.64],["Jun 2011",760547.01,1533,496.12],["Jul 2011",718076.12,1475,486.83],["Aug 2011",757841.38,1361,556.83],["Sep 2011",1056435.19,1837,575.09],["Oct 2011",1151263.73,2040,564.34],["Nov 2011",1503866.78,2769,543.11],["Dec 2011",637790.33,819,778.74],
] as const;
const scatter = [[13851,174156.54],[80995,168469.6],[37580,104284.24],[18283,99445.23],[48371,94159.81],[78033,81700.92],[30739,66870.03],[19329,64875.59],[36362,58927.62],[10302,54096.36],[8320,42513.48],[21448,42401.01],[11651,40633.38],[61,39619.5],[5487,38133.64],[7483,38108.89],[8695,37082.13],[6012,35966.92],[19232,35572.36],[36749,34288.67]] as const;
const productConcentration = [["Top 1%",19.57],["Top 5%",46.14],["Top 10%",62.27],["Top 20%",79.18],["Top 50%",96.31]] as const;
const customerConcentration = [["Top 1%",32.06],["Top 5%",50.46],["Top 10%",61.45],["Top 20%",74.68],["Top 50%",92.19]] as const;
const cancellations = [["Dec 2010",326,74789.12],["Jan 2011",260,131364.3],["Feb 2011",219,25569.24],["Mar 2011",318,34372.28],["Apr 2011",240,44601.5],["May 2011",314,47202.51],["Jun 2011",329,70616.78],["Jul 2011",270,37921.08],["Aug 2011",278,54333.75],["Sep 2011",333,38902.55],["Oct 2011",362,84274.63],["Nov 2011",441,47740.08],["Dec 2011",146,205124.67]] as const;
const snippets = [
  ["01 · Data Loading", "Load the complete UCI record set directly through the UCI ML Repository package.", `from ucimlrepo import fetch_ucirepo\n\nonline_retail = fetch_ucirepo(id=352)\ndf = online_retail.data.original.copy()\nprint(df.shape)\nprint(df.head())`],
  ["02 · Data Quality Audit", "Measure the issues that can materially affect sales and customer analysis before making cleaning decisions.", `missing = (\n    df.isna().sum().to_frame("missing_rows")\n      .assign(missing_pct=lambda x: x["missing_rows"] / len(df) * 100)\n      .sort_values("missing_rows", ascending=False)\n)\nduplicate_rows = df.duplicated().sum()\nis_cancelled = df["InvoiceNo"].astype(str).str.startswith("C")\nnegative_quantity = (df["Quantity"] < 0).sum()\ninvalid_price = (df["UnitPrice"] <= 0).sum()`],
  ["03 · Feature Engineering", "Create the transaction-level revenue measure and analytical sales view.", `df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])\ndf["Revenue"] = df["Quantity"] * df["UnitPrice"]\n\nsales = df.loc[\n    (~df["InvoiceNo"].astype(str).str.startswith("C"))\n    & (df["Quantity"] > 0)\n    & (df["UnitPrice"] > 0)\n].drop_duplicates().copy()`],
  ["04 · Sales Analysis", "Calculate monthly revenue, orders and average order value.", `total_revenue = sales["Revenue"].sum()\norders = sales["InvoiceNo"].nunique()\nunits = sales["Quantity"].sum()\naov = total_revenue / orders\n\nmonthly = (\n    sales.assign(Month=sales["InvoiceDate"].dt.to_period("M"))\n         .groupby("Month")\n         .agg(Revenue=("Revenue", "sum"), Orders=("InvoiceNo", "nunique"))\n         .reset_index()\n)\nmonthly["AOV"] = monthly["Revenue"] / monthly["Orders"]`],
  ["05 · Product Analysis", "Compare product volume with revenue and measure product revenue concentration.", `product_sales = sales.groupby(["StockCode", "Description"]).agg(\n    Revenue=("Revenue", "sum"),\n    Units=("Quantity", "sum")\n).reset_index()\n\nservice_terms = r"postage|manual|amazon fee|bank charges|discount|samples?|dotcom|adjustment|check"\nproducts = product_sales[\n    ~product_sales["Description"].fillna("").str.contains(service_terms, case=False, regex=True)\n].sort_values("Revenue", ascending=False)`],
  ["06 · Customer Analysis", "Calculate customer revenue and measure how concentrated revenue is among identified customers.", `customer_sales = sales.dropna(subset=["CustomerID"]).copy()\n\ncustomer_summary = (\n    customer_sales.groupby("CustomerID")\n    .agg(Revenue=("Revenue", "sum"), Orders=("InvoiceNo", "nunique"))\n    .reset_index()\n    .sort_values("Revenue", ascending=False)\n)\n\nfor pct in [1, 5, 10, 20, 50]:\n    n = int(np.ceil(len(customer_summary) * pct / 100))\n    share = customer_summary.head(n)["Revenue"].sum() / customer_summary["Revenue"].sum() * 100\n    print(f"Top {pct}%: {share:.2f}% of revenue")`],
  ["07 · Cancellation Analysis", "Measure cancelled invoices and cancelled value by month.", `cancelled = df[df["InvoiceNo"].astype(str).str.startswith("C")].copy()\n\ncancelled_monthly = (\n    cancelled.assign(Month=cancelled["InvoiceDate"].dt.to_period("M"))\n    .groupby("Month")\n    .agg(\n        CancelledInvoices=("InvoiceNo", "nunique"),\n        CancelledUnits=("Quantity", lambda x: -x[x < 0].sum()),\n        CancelledValue=("Revenue", lambda x: -x[x < 0].sum()),\n    )\n    .reset_index()\n)`],
] as const;

const gbp = (v:number) => `£${v.toLocaleString("en-GB", {maximumFractionDigits:0})}`;
function BarList({ data, percent=false }: {data: readonly (readonly [string,number])[]; percent?:boolean}) {
  const max = Math.max(...data.map(x=>x[1]));
  return <div className="space-y-4">{data.map((x,i)=><div key={x[0]}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="font-medium">{i+1}. {x[0]}</span><span className="font-semibold text-primary">{percent ? `${x[1].toFixed(2)}%` : gbp(x[1])}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${x[1]/max*100}%`}} /></div></div>)}</div>;
}
function ChartBox({title,description,children}:{title:string;description:string;children:React.ReactNode}) { return <div className="card-surface p-7"><h3 className="text-lg font-bold tracking-tight">{title}</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{description}</p><div className="mt-5 h-88 w-full">{children}</div></div>; }
function StaticLine({values,labels,formatter,yLabel}:{values:number[];labels:string[];formatter:(v:number)=>string;yLabel:string}) {
  const min=Math.min(...values), max=Math.max(...values), range=max-min||1, w=920, h=330, left=82, right=20, top=25, bottom=78;
  const px=(i:number)=>left+i/(values.length-1)*(w-left-right); const py=(v:number)=>h-bottom-(v-min)/range*(h-top-bottom);
  const points=values.map((v,i)=>`${px(i)},${py(v)}`).join(" ");
  const ticks=[0,0.25,0.5,0.75,1].map(t=>min+t*range);
  return <svg viewBox={`0 0 ${w} ${h}`} className="h-full w-full" role="img" aria-label={`${yLabel} over time`}>
    {ticks.map((v,i)=><g key={i}><line x1={left} y1={py(v)} x2={w-right} y2={py(v)} stroke="currentColor" opacity=".1"/><text x={left-9} y={py(v)+4} textAnchor="end" fontSize="13" fill="currentColor" opacity=".65">{formatter(v)}</text></g>)}
    <line x1={left} y1={top} x2={left} y2={h-bottom} stroke="currentColor" opacity=".2"/><line x1={left} y1={h-bottom} x2={w-right} y2={h-bottom} stroke="currentColor" opacity=".2"/>
    <polyline points={points} fill="none" stroke="currentColor" strokeWidth="3"/>
    {values.map((v,i)=><circle key={i} cx={px(i)} cy={py(v)} r="3" fill="currentColor"/>) }
    {labels.map((label,i)=><text key={label} x={px(i)} y={h-bottom+17} textAnchor="end" fontSize="12" fill="currentColor" opacity=".7" transform={`rotate(-45 ${px(i)} ${h-bottom+17})`}>{label}</text>)}
    <text x="22" y={(top+h-bottom)/2} textAnchor="middle" fontSize="13" fontWeight="600" fill="currentColor" opacity=".7" transform={`rotate(-90 22 ${(top+h-bottom)/2})`}>{yLabel}</text>
    <text x={(left+w-right)/2} y={h-4} textAnchor="middle" fontSize="13" fontWeight="600" fill="currentColor" opacity=".7">Month</text>
  </svg>;
}
function StaticBars({values, labels, formatter, yLabel, xLabel}:{values:number[];labels:string[];formatter:(v:number)=>string;yLabel:string;xLabel:string}) {
  const max=Math.max(...values), w=920, h=330, left=82, right=20, top=25, bottom=78, plotH=h-top-bottom, plotW=w-left-right;
  const barW=Math.min(46, plotW/values.length*0.62);
  return <svg viewBox={`0 0 ${w} ${h}`} className="h-full w-full" role="img" aria-label={`${yLabel} by ${xLabel}`}>
    {[0,0.25,0.5,0.75,1].map((t,i)=>{const y=h-bottom-t*plotH; const value=t*max; return <g key={i}><line x1={left} y1={y} x2={w-right} y2={y} stroke="currentColor" opacity=".1"/><text x={left-9} y={y+4} textAnchor="end" fontSize="13" fill="currentColor" opacity=".65">{formatter(value)}</text></g>})}
    <line x1={left} y1={top} x2={left} y2={h-bottom} stroke="currentColor" opacity=".2"/><line x1={left} y1={h-bottom} x2={w-right} y2={h-bottom} stroke="currentColor" opacity=".2"/>
    {values.map((v,i)=>{const x=left+(i+0.5)*plotW/values.length; const barH=v/max*plotH; return <g key={labels[i]}><rect x={x-barW/2} y={h-bottom-barH} width={barW} height={barH} rx="4" fill="currentColor" opacity=".85"/><text x={x} y={h-bottom-barH-7} textAnchor="middle" fontSize="12" fill="currentColor" opacity=".75">{formatter(v)}</text><text x={x} y={h-bottom+17} textAnchor="end" fontSize="12" fill="currentColor" opacity=".7" transform={`rotate(-45 ${x} ${h-bottom+17})`}>{labels[i]}</text></g>})}
    <text x="22" y={(top+h-bottom)/2} textAnchor="middle" fontSize="13" fontWeight="600" fill="currentColor" opacity=".7" transform={`rotate(-90 22 ${(top+h-bottom)/2})`}>{yLabel}</text>
    <text x={(left+w-right)/2} y={h-4} textAnchor="middle" fontSize="13" fontWeight="600" fill="currentColor" opacity=".7">{xLabel}</text>
  </svg>;
}
function StaticScatter() {
  const maxX=Math.max(...scatter.map(x=>x[0])), maxY=Math.max(...scatter.map(x=>x[1])), w=920, h=330, left=88, right=20, top=25, bottom=70;
  const x=(v:number)=>left+v/maxX*(w-left-right), y=(v:number)=>h-bottom-v/maxY*(h-top-bottom);
  const xTicks=[0,0.25,0.5,0.75,1], yTicks=[0,0.25,0.5,0.75,1];
  return <svg viewBox={`0 0 ${w} ${h}`} className="h-full w-full" role="img" aria-label="Product units sold versus revenue">
    {yTicks.map((t,i)=><g key={`y-${i}`}><line x1={left} y1={y(t*maxY)} x2={w-right} y2={y(t*maxY)} stroke="currentColor" opacity=".1"/><text x={left-9} y={y(t*maxY)+4} textAnchor="end" fontSize="13" fill="currentColor" opacity=".65">{gbp(t*maxY)}</text></g>)}
    {xTicks.map((t,i)=><g key={`x-${i}`}><line x1={x(t*maxX)} y1={top} x2={x(t*maxX)} y2={h-bottom} stroke="currentColor" opacity=".07"/><text x={x(t*maxX)} y={h-bottom+17} textAnchor="middle" fontSize="13" fill="currentColor" opacity=".65">{Math.round(t*maxX/1000)}k</text></g>)}
    <line x1={left} y1={top} x2={left} y2={h-bottom} stroke="currentColor" opacity=".2"/><line x1={left} y1={h-bottom} x2={w-right} y2={h-bottom} stroke="currentColor" opacity=".2"/>
    {scatter.map((p,i)=><circle key={i} cx={x(p[0])} cy={y(p[1])} r="5" fill="currentColor" opacity=".75"/>)}
    <text x="15" y="16" fontSize="13" fontWeight="600" fill="currentColor" opacity=".7" transform="rotate(-90 15 16)">Revenue (£)</text>
    <text x={(left+w-right)/2} y={h-4} textAnchor="middle" fontSize="13" fontWeight="600" fill="currentColor" opacity=".7">Units sold</text>
  </svg>;
}

export function RetailSalesIntelligence() {
  const [activeCode,setActiveCode]=useState(0);
  const revenue=monthly.map(x=>x[1]), orders=monthly.map(x=>x[2]), aov=monthly.map(x=>x[3]);
  const cancelInvoices=cancellations.map(x=>x[1]), cancelValue=cancellations.map(x=>x[2]), months=monthly.map(x=>x[0]);
  return <div className="min-h-screen bg-background text-foreground antialiased selection:bg-primary/20"><SiteNav/><main className="pb-20">
    <header className="border-b border-border bg-surface/60"><div className="container-page py-10 sm:py-14"><Link to="/" hash="projects" className="inline-flex items-center gap-2 text-xs font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5"/> Back to all projects</Link><div className="mt-6 flex flex-wrap items-center gap-2"><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">Business Analytics</span><span className="text-xs text-muted-foreground">•</span><span className="text-xs text-muted-foreground">Python · Pandas · EDA</span></div><h1 className="mt-4 max-w-4xl text-3xl font-bold tracking-tight text-balance sm:text-4xl lg:text-5xl">Retail Sales Intelligence &amp; Customer Analytics</h1><p className="mt-4 max-w-3xl text-base leading-relaxed text-muted-foreground sm:text-lg">Turning 541,909 transaction-line records into a commercial view of sales performance, product concentration, customer value, seasonality, and market opportunity.</p><div className="mt-6 flex flex-wrap items-center gap-2">{["Python","Pandas","NumPy","Matplotlib","Seaborn","Business Analytics"].map(x=><span key={x} className="rounded-md border border-border bg-card px-2.5 py-1 text-xs font-medium text-muted-foreground shadow-2xs">{x}</span>)}</div><div className="mt-7 flex flex-wrap gap-3"><a href={sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-2 text-xs font-semibold text-foreground hover:bg-accent">UCI Dataset <ExternalLink className="size-3.5"/></a><a href="#code" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground"><Code2 className="size-3.5"/> Show Code</a></div></div></header>
    <div className="container-page mt-12 space-y-16">
      <section><div className="flex items-center gap-2 text-primary"><BarChart3 className="size-5"/><h2 className="text-sm font-semibold uppercase tracking-wider">Executive Snapshot</h2></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{kpis.map(k=><div key={k[0]} className="card-surface p-5"><span className="text-xs font-medium text-muted-foreground">{k[0]}</span><p className="mt-2 text-3xl font-extrabold tracking-tight">{k[1]}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{k[2]}</p></div>)}</div></section>
      <section className="grid gap-8 lg:grid-cols-2"><div className="card-surface p-7"><div className="flex items-center gap-2 text-primary"><Users className="size-5"/><h2 className="text-lg font-bold">Business Question</h2></div><p className="mt-4 text-sm leading-relaxed text-muted-foreground">Management needs to understand where revenue comes from, when demand peaks, which products drive sales, how dependent the business is on its highest-value customers, and which markets deserve attention.</p><div className="mt-5 border-t border-border pt-5"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Business Objective</p><p className="mt-2 text-sm leading-relaxed text-foreground">Understand sales performance, identify the products and customers driving revenue, and highlight opportunities across different markets.</p></div></div><div className="card-surface p-7"><div className="flex items-center gap-2 text-primary"><Globe2 className="size-5"/><h2 className="text-lg font-bold">Dataset</h2></div><p className="mt-4 text-sm leading-relaxed text-muted-foreground">The UCI Online Retail dataset contains transactions from a UK-based non-store online retailer between 1 December 2010 and 9 December 2011. It contains 541,909 records and eight transaction fields.</p><div className="mt-5 grid grid-cols-2 gap-3 text-xs">{["541,909 rows","8 fields","38 countries","Dec 2010–Dec 2011"].map(x=><div key={x} className="rounded-lg border border-border bg-surface p-3 font-medium text-muted-foreground">{x}</div>)}</div></div></section>
      <section className="grid gap-8 lg:grid-cols-2"><div className="card-surface p-7"><span className="text-xs font-semibold uppercase tracking-wider text-primary">Product performance</span><h2 className="mt-1 text-2xl font-bold">Top products by revenue</h2><p className="mt-2 text-xs text-muted-foreground">Service and postage codes are separated from the product story where appropriate.</p><div className="mt-6"><BarList data={products}/></div></div><div className="card-surface p-7"><span className="text-xs font-semibold uppercase tracking-wider text-primary">Market concentration</span><h2 className="mt-1 text-2xl font-bold">Revenue is heavily concentrated in the UK</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">The international share is meaningful, but no individual overseas market approaches the domestic revenue base.</p><div className="mt-7"><BarList data={countries} percent/></div></div></section>
      <section><div className="mb-5"><span className="text-xs font-semibold uppercase tracking-wider text-primary">Sales performance</span><h2 className="mt-1 text-2xl font-bold">Revenue, orders and average order value over time</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">Monthly views make the seasonal ramp visible and separate changes in revenue from changes in order volume and order value.</p></div><div className="grid gap-8 lg:grid-cols-2"><ChartBox title="Monthly revenue" description="Completed-sales revenue by month."><StaticLine values={revenue} labels={months} formatter={gbp} yLabel="Revenue (£)"/></ChartBox><ChartBox title="Monthly orders" description="Unique completed invoices by month."><StaticBars values={orders} labels={months} formatter={v=>v.toLocaleString()} yLabel="Completed orders" xLabel="Month"/></ChartBox><ChartBox title="Average order value" description="Revenue divided by completed orders for each month."><StaticLine values={aov} labels={months} formatter={gbp} yLabel="Average order value (£)"/></ChartBox></div></section>
      <section><div className="mb-5"><span className="text-xs font-semibold uppercase tracking-wider text-primary">Product economics</span><h2 className="mt-1 text-2xl font-bold">Volume does not always translate directly into revenue</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">The scatter view compares units sold with revenue across the highest-revenue merchandise products.</p></div><ChartBox title="Product volume vs revenue" description="Top 20 merchandise products by revenue; each point represents one product."><StaticScatter/></ChartBox></section>
      <section className="grid gap-8 lg:grid-cols-2"><ChartBox title="Product revenue concentration" description="Share of merchandise revenue generated by the highest-revenue product groups."><StaticBars values={productConcentration.map(x=>x[1])} labels={productConcentration.map(x=>x[0])} formatter={v=>`${v.toFixed(2)}%`} yLabel="Revenue share (%)" xLabel="Highest-revenue product group"/></ChartBox><ChartBox title="Customer revenue concentration" description="Share of identified-customer revenue generated by the highest-value customer groups."><StaticBars values={customerConcentration.map(x=>x[1])} labels={customerConcentration.map(x=>x[0])} formatter={v=>`${v.toFixed(2)}%`} yLabel="Revenue share (%)" xLabel="Highest-value customer group"/></ChartBox></section>
      <section><div className="mb-5"><span className="text-xs font-semibold uppercase tracking-wider text-primary">Cancellations &amp; returns</span><h2 className="mt-1 text-2xl font-bold">Cancelled invoices and cancelled value vary by month</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">Cancelled invoice numbers are identified by the <code>C</code> prefix. The analysis separates cancellation frequency from the value associated with cancelled lines.</p></div><div className="grid gap-8 lg:grid-cols-2"><ChartBox title="Cancelled invoices by month" description="Unique invoice numbers marked as cancelled."><StaticBars values={cancelInvoices} labels={months} formatter={v=>v.toLocaleString()} yLabel="Cancelled invoices" xLabel="Month"/></ChartBox><ChartBox title="Cancelled value by month" description="Absolute value of negative cancelled sales lines."><StaticLine values={cancelValue} labels={months} formatter={gbp} yLabel="Cancelled value (£)"/></ChartBox></div><div className="mt-4 grid gap-4 sm:grid-cols-3"><div className="card-surface p-5"><span className="text-xs text-muted-foreground">Cancelled invoices</span><p className="mt-2 text-2xl font-bold">3,836</p><p className="mt-1 text-xs text-muted-foreground">14.81% of 25,900 invoice numbers</p></div><div className="card-surface p-5"><span className="text-xs text-muted-foreground">Cancelled units</span><p className="mt-2 text-2xl font-bold">277,574</p><p className="mt-1 text-xs text-muted-foreground">Based on negative-quantity cancelled lines</p></div><div className="card-surface p-5"><span className="text-xs text-muted-foreground">Cancelled value</span><p className="mt-2 text-2xl font-bold">£896,812</p><p className="mt-1 text-xs text-muted-foreground">Absolute value of cancelled lines</p></div></div></section>
      <section id="code" className="scroll-mt-24"><div className="flex items-center gap-2 text-primary"><Code2 className="size-5"/><h2 className="text-2xl font-bold">Show Code</h2></div><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Selected Python used for the retail analysis.</p><div className="mt-6 overflow-hidden rounded-xl border border-border bg-card"><div className="flex flex-wrap border-b border-border">{snippets.map((s,i)=><button key={s[0]} onClick={()=>setActiveCode(i)} className={`px-4 py-3 text-xs font-semibold ${activeCode===i?"bg-primary/10 text-primary":"text-muted-foreground hover:bg-accent hover:text-foreground"}`}>{s[0]}</button>)}</div><div className="p-5"><p className="mb-3 text-sm text-muted-foreground">{snippets[activeCode][1]}</p><CodeBlock code={snippets[activeCode][2]} language="python"/></div></div></section>
    </div></main><SiteFooter/></div>;
}
